CREATE DATABASE CLINICA;
GO

USE CLINICA;
GO

CREATE TABLE ClinicaVeterinaria(
IdClinica INT PRIMARY KEY IDENTITY(1,1),
Endereco VARCHAR(50),
RazaoSocial VARCHAR(20)
);
GO


CREATE TABLE Veterinario(
IdVeterinario INT PRIMARY KEY IDENTITY(1,1),
IdClinica INT FOREIGN KEY REFERENCES ClinicaVeterinaria(IdClinica),
NomeVeterinario VARCHAR(20),
CRMV CHAR(4)
);
GO

CREATE TABLE Dono(
IdDono INT PRIMARY KEY IDENTITY(1,1),
NomeDono VARCHAR(20)
);
GO

CREATE TABLE Pet(
IdPet INT PRIMARY KEY IDENTITY(1,1),
IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
NomePet VARCHAR(10)
);
GO

CREATE TABLE Consulta(
IdConsulta INT PRIMARY KEY IDENTITY(1,1),
IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
IdPet INT FOREIGN KEY REFERENCES Pet(IdPet),
DataConsulta DATE,
NomeVeterinario VARCHAR(20),
Pet Varchar(10),
DescricaoConsulta VARCHAR (30)
);
GO


CREATE TABLE Raca(
IdRaca INT PRIMARY KEY IDENTITY(1,1),
IdPet INT FOREIGN KEY REFERENCES Pet(IdPet),
NomeRaca VARCHAR(25) NOT NULL,
NomePet VARCHAR (10) NOT NULL
);
GO

CREATE TABLE TipoPet(
IdTipo INT PRIMARY KEY IDENTITY(1,1),
IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
_tipoPet VARCHAR(20) NOT NULL
);
GO