CREATE DATABASE MercadoPago;
GO

USE UNIDAS;
GO

CREATE TABLE PESSOA(
IdPessoa INT PRIMARY KEY IDENTITY(1,1),
NomePessoa VARCHAR(20) NOT NULL UNIQUE
);
GO

CREATE TABLE TELEFONE (
IdTelefone INT PRIMARY KEY IDENTITY(1,1),
IdPessoa INT FOREIGN KEY REFERENCES PESSOA(IdPessoa),
NumeroTelefone CHAR(11) NOT NULL
);
GO

CREATE TABLE EMAIL (
IdEmail INT PRIMARY KEY IDENTITY(1,1),
IdPessoa INT FOREIGN KEY REFERENCES PESSOA(IdPessoa),
_email VARCHAR(256) NOT NULL UNIQUE
);
GO

CREATE TABLE CNH (
IdCNH INT PRIMARY KEY IDENTITY(1,1),
IdPessoa INT FOREIGN KEY REFERENCES PESSOA(IdPessoa),
NumeroCNH CHAR(11) NOT NULL UNIQUE
);
GO