CREATE DATABASE CLINICA;
GO

USE CLINICA;
GO

CREATE TABLE ClinicaVeterinaria(
IdClinica INT PRIMARY KEY IDENTITY(1,1),
Endereco VARCHAR(50)
);
GO

CREATE TABLE Veterinario(
IdVeterinario INT PRIMARY KEY IDENTITY(1,1),
IdClinica INT FOREIGN KEY REFERENCES ClinicaVeterinaria(IdClinica),
NomeVeterinario VARCHAR(20)
);
GO

CREATE TABLE Dono(
IdDono INT PRIMARY KEY IDENTITY(1,1),
NomeDono VARCHAR(20)
);
GO

CREATE TABLE Pet(
IdPet INT PRIMARY KEY IDENTITY(1,1),
IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
NomePet VARCHAR(10)
);
GO